name: release-lib-example-b

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/lib-example-b

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: load cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: npm test
        run: npm test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    name: Release
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: load cache
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build
        if: success()
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run build
      - name: Release
        if: success()
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: 'npx semantic-release'
